# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
      - 'mvp'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # < 12.0.0 is not supported because jest and syntax
        # > 16.0.0 is not supported because of tfjs obscure error
        #send help
        node-version: [ 16.x, 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Test Coverage Report"
          message: ${{ steps.coverage.outputs.report }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          recreate: true
          delete: true
